apiVersion: v1
kind: LimitRange
metadata:
  name: recursos
spec:
  limits:
    - default: #Límite default para cada container
        memory: 512Mi
        cpu: 1
      defaultRequest: #Límite otorgado para contenedor
        memory: 256Mi
        cpu: 0.5
      #Límite minimo y máximo que un container puede pedir
      max:
        memory: 1Gi
        cpu: 4
      min:
        memory: 128Mi
        cpu: 0.5
      type: Container
