apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: db
      name: mongodb
  serviceName: mongodb-svc #Servicio headless
  replicas: 3
  template:
    metadata:
      labels:
        app: db
        name: mongodb    
    spec:
      terminationGracePeriodSeconds: 10 #Tiempo de gracia que se le da al Pod para parar.
      containers:
      - name: mongo
        image: mongo:3.6  
        #Comando para encender mongo      
        command: 
          - mongod
        args: 
          - --bind_ip=0.0.0.0
          - --replSet=rs0 #Nombre del replica set. Todos los miembros dle cluster usan este nombre
          - --dbpath=/data/db          
        livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
  #Crear de forma dinámica los PVs y los PVCs
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage      
      spec:
        storageClassName: estado
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
