apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: contenedor1
      image: ubuntu
      command: [ "/bin/sh", "-c", "sleep 1000000" ]
      volumeMounts: #Montar volumen creado
      - name: volumen-secretos
        mountPath: /tmp/datos
  volumes: 
    - name: volumen-secretos
      secret: #De tipo secret
        secretName: secreto-volumen #Secret existente
  restartPolicy: Never
