apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: test-container
      image: gcr.io/google-samples/node-hello:1.0
      envFrom:
        - configMapRef:
            name: datos-mysql-env
      # env:
      #   # Define the environment variable
      #   - name: DATOS_MYSQL
      #     valueFrom:
      #       configMapKeyRef:
      #         name: cf-mysql
      #         key: datos_mysql.properties

  restartPolicy: Never
