apiVersion: v1 
kind: Pod
metadata:
  name: apache1
spec:
  affinity:
     nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          #Los terminos del selector
          nodeSelectorTerms:
          #Condiciones del selector
          - matchExpressions:
            #La label 'equipo' debe coincidir con alguno de los values
             - key: equipo
               operator: In
               values:
               - desarrollo-web
               - desarrollo-python
  containers:
  - name: apache1
    image: httpd

