apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  #Nombre de la clase
  storageClassName: sistemaficheros
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  #Ubicación en mi maquina (nodo)
  hostPath:
    path: "/mnt/data"
