apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-dinamica
#Se utilizará el provisioner del minikube
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
reclaimPolicy: Delete