apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-d
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template: 
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-sonda
        image: apasoft/sonda-web:latest
        ports:
        - containerPort: 80
        #Sonda HTTP
        livenessProbe:
            httpGet:
                path: /sonda.html
                port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
