apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
        #Creacion convencional de variable
        - name: MI_VARIABLE
          value: "algun valor"

        #Creacion con SECRETS
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              #Nombre del secret
              name: db-credentials
              #Key del secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
      ports:
        - containerPort: 80
