apiVersion: v1
kind: LimitRange
metadata:
  name: recursos
spec:
  limits:
  #Para aquellos elementos que se creen sin especificar recursos
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 0.5
    max:
      memory: 1Gi
      cpu: 4
    min:
      memory: 128Mi
      cpu: 0.5
    #Puede ser Container o Pod
    #Container es para container de cada pod
    type: Container
