apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: binding-sa
   namespace: default
#El SA afectado
subjects:
- kind: ServiceAccount
  name: sa1 
#El Role a bindear
roleRef:
  kind: Role 
  name: sa-role
  apiGroup: rbac.authorization.k8s.io
